In [3]:
# degree() function
import numpy as np
import math
nparray = [0,math.pi/2,np.pi/3,np.pi]
print ("Radian values : \n", nparray) 
DegreeValues = np.degrees(nparray) 
print ("\nDegree values : \n", DegreeValues) 

Radian values : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Degree values : 
 [  0.  90.  60. 180.]


In [7]:

# round_() function

 
in_array = [.2, 1.9, 5.5, 1.5, .5, 10.2]
print ("Input array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.2, 1.9, 5.5, 1.5, 0.5, 10.2]

Rounded values : 
 [ 0.  2.  6.  2.  0. 10.]


In [9]:
# divide() function
import numpy as np
 

arr1 = [2, 33, 1, 27, 25]
arr2 = [3, 3, 2, 9, 5]
print ("arr1      : ", arr1)
print ("arr2      : ", arr2)
 

out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)


arr1      :  [2, 33, 1, 27, 25]
arr2      :  [3, 3, 2, 9, 5]

Output array : 
 [ 0.66666667 11.          0.5         3.          5.        ]


In [10]:
# maximum() function
import numpy as np 
num1 = 100
num2 = 218
  
print ("Input  number1 : ", num1) 
print ("Input  number2 : ", num2)  
    
out = np.maximum(num1, num2)  
print ("maximum of 100 and 218 : ", out)  


Input  number1 :  100
Input  number2 :  218
maximum of 100 and 218 :  218


In [12]:
# negative() function
import numpy as np 
num = 103
  
print ("Input  number : ", num) 
    
out = np.negative(num)  
print ("negative of input number : ", out)  

Input  number :  103
negative of input number :  -103


In [ ]:
# power() function
import numpy as np 
  
arr1 = [2, 2, 2, 2, 2] 
arr2 = [2, 3, 4, 5, 6] 
print ("arr1         : ", arr1) 
print ("arr1         : ", arr2) 
 
out = np.power(arr1, arr2) 
print ("\nOutput array : ", out) 

In [15]:
# square () function 
  
import numpy as np 
  
arr1 = [1, -5, 12, -6] 
print ("Square Value of arr1 : \n", np.square(arr1)) 
  
arr2 = [55 ,-26] 
print ("\nSquare Value of arr2 : ", np.square(arr2)) 


Square Value of arr1 : 
 [  1  25 144  36]

Square Value of arr2 :  [3025  676]


In [20]:
# ndim()
# shape()
# size ()
import numpy as np

i = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
print(i.ndim) # Prints 2
print(i.shape) # Prints (3L, 3L)
print(i.size) # Prints 9

2
(3, 3)
9


In [24]:
# mean()
# sum()
# sin()
import numpy as np

x = np.array([1,2,3,4,5])
print(x)
avg = x.mean()
print(avg)
sum = x.sum()
print(sum)
sx = np.sin(x)
print(sx)

[1 2 3 4 5]
3.0
15
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [33]:
# random.randint()
from numpy import random

x = random.randint(20)

print(x)


3


In [35]:
# add()
import numpy as np

a = [1, 2, 3, 4]
b = [4, 5, 6, 7]
c = np.add(a, b)

print(c)

[ 5  7  9 11]


In [36]:
#discrete difference diff() : subtracting two successive elements
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [37]:
# prod()
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)


24


In [38]:
# Cummulative product cumprod() : taking the product partially.
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [39]:
#add()
#sum()
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)
print(newarr)
newarr = np.sum([arr1, arr2])
print(newarr)

[2 4 6]
12


In [40]:
#subtract()
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [42]:
#unique()
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [43]:
#union1d()
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [44]:
#intersect1d()
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)


[3 4]


In [47]:
#linspace() function returns evenly spaced numbers over a specified interval defined by the first two arguments of the function. 
#The number of samples generated is specified by the third argument num
import numpy as np
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
#repeat()
import numpy as np
np.repeat('2020',5)

array(['2020', '2020', '2020', '2020', '2020'], dtype='<U4')